services:
  windows:
    image: dockurr/windows
    container_name: hspm-windows
    environment:
      VERSION: "10"
      USERNAME: "MAIN"
      PASSWORD: "admin@123"
      RAM_SIZE: "8G"
      CPU_CORES: "64"
      DISK_SIZE: "256G"
      DISK2_SIZE: "512G"
    devices:
      - dev/kvm
      - dev/net/tun
    cap_add:
      - NET_ADMIN
    ports: 
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    stop_grace_period: 2m
